### ISSUE TITLE
Cannot deploy docker stack permission issue

### ISSUE THREAD

**Issue by p6002** [tubearchivist/tubearchivist#442]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Synology

### Your installation or setup question

I am trying to run stack, I have configured compose file correctly, only **es** reports a problem with permissions.
I read the readme and added admin account permissions for /volume1/docker/tube/es, the same as in compose file and the problem still occurs.

Later I added the default volume to es:
https://pastebin.com/NNuwW5Y3
and it still does not work, but returns such a log:
https://pastebin.com/WzLrFc21
Here is tubearchive log:
https://pastebin.com/Wsk9sg8s

After 3 hours stinn nothing, I change even images, here is latest compose:
https://pastebin.com/CJLgbERg

This is log, when es file is  set to my own directory with correct permissions:

### Relevant log output

```shell
ctions
 
 
 
      
Created elasticsearch keystore in /usr/share/elasticsearch/config/elasticsearch.keystore
unable to install syscall filter:  | @timestamp=2023-02-25T11:33:26.384Z log.level=WARN ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=main log.logger=org.elasticsearch.bootstrap.JNANatives elasticsearch.node.name=386b312f4b9d elasticsearch.cluster.name=docker-cluster error.type=java.lang.UnsupportedOperationException error.message=seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed error.stack_trace=java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:331)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:622)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:251)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:102)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.Elasticsearch.initializeNatives(Elasticsearch.java:269)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.Elasticsearch.initPhase2(Elasticsearch.java:166)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:66)
fatal exception while booting Elasticsearch | @timestamp=2023-02-25T11:33:26.534Z log.level=ERROR ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=main log.logger=org.elasticsearch.bootstrap.Elasticsearch elasticsearch.node.name=386b312f4b9d elasticsearch.cluster.name=docker-cluster error.type=java.lang.IllegalStateException error.message=Unable to access 'path.repo' (/usr/share/elasticsearch/data/snapshot) error.stack_trace=java.lang.IllegalStateException: Unable to access 'path.repo' (/usr/share/elasticsearch/data/snapshot)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:66)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:252)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.Security.createPermissions(Security.java:178)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.Security.configure(Security.java:125)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.Elasticsearch.initPhase2(Elasticsearch.java:186)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:66)
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/snapshot
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:330)
	at org.elasticsearch.server@8.6.0/org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:64)
	... 5 more

```

**Comment by lamusmaser** [comment]
You have several conflicts going on, which is why this is occurring.

1. ElasticSearch with TubeArchivist requires that you include an environment variable, `path.repo`. This is expected to be underneath the ES persistent storage, within the associated volume for `/usr/share/elasticsearch/data/`, in a subdirectory called `snapshot`.
2. For Synology, we list the permissions required for the `es` directory [here](https://github.com/tubearchivist/tubearchivist/wiki/Installation#8-change-permissions---cli-required). These will be the same regardless of deploying through the Synology Docker manager or via docker-compose directly. _This needs to be confirmed, please provide the `ls -ln` of that directory._
3. If you have further issues beyond this, let's look into it further. However, we will need to review the _current_ versions of the following to ensure that we can expedite this information, especially for access issues like you are seeing:
  - `docker-compose.yml`
  - Permissions of relevant directories (using `ls -ln`)
  - logs from affected containers, including TA and ES for this issue

Since we have several versions of the docker-compose and their associated logs, here is my recommendation:
1. Use the `docker-compose.yml` that has the volume mount to the ES directory (the latest compose provided).
2. Update the environment variable to include `path.repo`, as it is currently commented out.
3. Check the directory permissions on the directory `/volume1/docker/tubearchivist/es`. This is expected to match 1000:1000 ownership permissions. We also provide it with 0755 access permissions.
4. Rebuild the stack. If you continue to see an error after these steps, provide details back into this issue.

**Comment by nicolasshu** [comment]
I did encounter similar issues, and after I did set the permissions to be in accordance with the Synology guide:
```
total 0
drwxr-xr-x 1 1026  100 166 Feb 26 03:52 cache
drwxr-xr-x 1 1000 1000  98 Feb 26 05:37 es
drwxr-xr-x 1 1026  100   0 Feb 26 02:14 media
drwxr-xr-x 1  999  100  16 Feb 26 05:03 redis
```

it started working. Thank you very much, @lamusmaser!!

**Comment by p6002** [comment]
It doesn't work for me, the permissions I have are the same.

**Comment by nicolasshu** [comment]
From a very quick skim, I think you need to change your TA_HOST env variable. I'm not how now, but I'll send you my docker-compose later. Yeah, I think the documentation could be improved a little bit, and it also took me a little while to figure out the right configuration

**Comment by lamusmaser** [comment]
`TA_HOST` is only applicable for accessing the TA web application, this would not effect ES or the connection from TA to ES. Additionally, this configuration would be correct, assuming that @p6002 is accessing TA only via the IP address.

In terms of documentation that can be updated, @nicolasshu, could you please provide more details and I will take it into consideration. I haven't created a `docker-compose`-based document for Synology, yet, as it tends to align mostly with the current documentation.

Doing a `diff` compare between my working `yaml` and yours, there are only two major differences:
1. I am declaring my networks. I do this because I hide my backend services, however your method should be working (since you are port forwarding to the host, and then you accessing through the host).
2. As called out previously, the `path.repo` is commented in the "latest" compose. This would need to be active, but is non-restrictive to ES starting up.

I compared to my test instance for this, and I clear out for every unstable or testing release, and even test upgrades through it. Here is the script that is being performed:

### ytdl-test-repave.sh
```
#!/bin/bash

#Stop any potential containers that may be running or that exist
docker-compose down

#Clear existing paths
rm -rf /volume1/docker/tubearchivist-test/es/*
rm -rf /volume1/docker/tubearchivist-test/redis/*
rm -rf /volume1/TubeArchivist/cache-test/*
rm -rf /volume1/TubeArchivist/media-test/*

#Pull latest release
docker-compose pull
docker-compose up --force-recreate -d
```

### Directory Permissions
```
root@<hostname>:/volume1/docker/tubearchivist-test# ls -nl /volume1/docker/tubearchivist-test /volume1/TubeArchivist

/volume1/TubeArchivist:
total 0
d---------+ 1 1026  100    0 Feb 17 20:39 media-test
drwxrwxrwx  1    0    0  166 Feb 17 20:46 cache-test

/volume1/docker/tubearchivist-test:
total 12
-rwxr-xr-x  1 1031    0 2212 Feb 17 20:47 docker-compose.yml
drwxr-xr-x+ 1 1000 1000   98 Feb 27 15:04 es
drwxr-xr-x+ 1  999  100   16 Feb 27 14:34 redis
-rwxr-xr-x  1    0    0  240 Feb 19 10:35 update-ytdl.sh
-rwxr-xr-x  1    0    0  559 Jan 15 20:54 ytdl-test-repave.sh
```

I can completely understand if you don't want to work on this any further, but we are willing to determine what's going on with the configuration.

**Comment by p6002** [comment]
Here are my logs and the latest docker compose from a ubuntu virtual machine where everything is 1000:1000 by default.

Redis:
https://pastebin.com/0heD8BjN
Es:
https://pastebin.com/Z99QmGgy
Tubearchivist:
https://pastebin.com/AuxpwEMX
Compose:
https://pastebin.com/YA0PDZix

**Comment by lamusmaser** [comment]
I don't see any errors that would prevent it from running at this point in time, and all logs indicate that the services are working as expected.

So, from here, the only change that would be necessary is updating the `TA_HOST` to be either the IP address, hostname, or both so you can access it. Alternatively, you could have `tubearchivist.local` set to the IP address of the Ubuntu host, either via DNS or editing the `/etc/hosts` file.

In case you need to update the `TA_HOST` environment variable, it would be changed from:
```
      - TA_HOST=tubearchivist.local        # set your host name
```

into either:
#### IP Address
```
      - TA_HOST=192.168.X.X        # set your IP Address
```
#### Hostname
```
      - TA_HOST=domain.ext        # set your IP Address
```
#### Both
```
      - "TA_HOST=domain.ext 192.168.X.X"        # set your IP Address
```

**Comment by p6002** [comment]
I changed it and it still doesn't work. 

https://i.ibb.co/VJyS4H2/2023-02-28-001148.png

192.168.1.123 is the address of the virtual machine on the server with the address 192.168.1.169.

But I tried before within the synology server with address 192.168.1.163 and it didn't work either.

The firewall on the synology and on the other server are disabled. I am trying to connect from a windows computer with address 192.169.1.160 all devices on the same local network. 

There are about 40 containers running on the servers and they communicate with each other with no problems.

**Comment by bbilly1** [comment]
I'm not quite sure about Synology, they have different permissions, but for regular ubuntu VM and the like, the permissions on the ES folder should be `1000:0` as mentioned in the [common errors](https://github.com/tubearchivist/tubearchivist#permissions-for-elasticsearch). That should be the only permission you need to change.

**Comment by p6002** [comment]
> Here's my docker-compose file

Thanks, I used your compose as a template and it worked right away.

**Comment by nicolasshu** [comment]
Cool! What is it that you did wrong?

**Comment by p6002** [comment]
The main thing is instead of: REDIS_HOST=I gave my ip address, removed some unnecessary entries, marked in quotation marks environments in "es". I copied your compose and added my own data, so I don't know exactly what the problem was. I'm glad it finally works.
